services:
  db:
    image: "mcr.microsoft.com/mssql/server:2022-CU21-ubuntu-22.04"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password1"
      ACCEPT_EULA: "Y"
      # Developer / Express / Standard / Enterprise  / EnterpriseCore
      MSSQL_PID: Developer
      MSSQL_TCP_PORT: 1433
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  mongo:
    image: mongo:8
    ports:
      - "27017:27017"
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 10
    entrypoint:
      ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "myReplicaSet"]

  mongoClusterSetup:
    image: mongo:8
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./scripts:/app
    command:
      - bash
      - -c
      - ./app/mongo-init-replica-set.sh

  integration-tests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      mongoClusterSetup:
        condition: service_completed_successfully
    environment:
      - "TEST_DB_SERVER=db,1433"
      - "TEST_MONGO_CONNECTION=mongodb://mongo:27017/?directConnection=true"
    command: [ "./scripts/start-tests.sh" ]

  lint-formatter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    # Uncomment the following line to run the checker
    # command: [ "./scripts/start-check-formatting.sh" ]
    # Uncomment the following line to run the formatter
    command: [ "./scripts/start-formatter.sh" ]