using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;

using Microsoft.AspNetCore.TestHost;

using FluentAssertions;
using Xunit;

using EasyData.AspNetCore.AdminDashboard.Tests.Fixtures;

namespace EasyData.AspNetCore.AdminDashboard.Tests.EntityCrudTests
{
    public class EditTests : IClassFixture<AdminDashboardFixture>
    {
        private readonly HttpClient _client;

        public EditTests(AdminDashboardFixture fixture)
        {
            _client = fixture.GetTestHost().GetTestClient();
        }

        [Fact]
        public async Task EditForm_RendersPrefilled_ForExistingRecordAsync()
        {
            // Category Id=1 is "Italian"
            var response = await _client.GetAsync("/admin/Category/1/change/");
            var html = await response.Content.ReadAsStringAsync();

            response.StatusCode.Should().Be(HttpStatusCode.OK);
            html.Should().Contain("Change category");
            html.Should().Contain("Italian");
        }

        [Fact]
        public async Task EditForm_ContainsDeleteLinkAsync()
        {
            var response = await _client.GetAsync("/admin/Category/1/change/");
            var html = await response.Content.ReadAsStringAsync();

            html.Should().Contain("/admin/Category/1/delete/");
            html.Should().Contain("Delete");
        }

        [Fact]
        public async Task EditPost_UpdatesRecordAndRedirectsAsync()
        {
            var formData = new FormUrlEncodedContent(new[]
            {
                new KeyValuePair<string, string>("Name", "Italian Updated"),
                new KeyValuePair<string, string>("Description", "Updated description"),
                new KeyValuePair<string, string>("_save_action", "save"),
            });

            var response = await _client.PostAsync("/admin/Category/1/change/", formData);

            response.StatusCode.Should().Be(HttpStatusCode.Redirect);
            response.Headers.Location.ToString().Should().Contain("/admin/Category/");
        }

        [Fact]
        public async Task EditPost_SaveAndContinue_RedirectsToSameFormAsync()
        {
            var formData = new FormUrlEncodedContent(new[]
            {
                new KeyValuePair<string, string>("Name", "Italian Final"),
                new KeyValuePair<string, string>("Description", "Final description"),
                new KeyValuePair<string, string>("_save_action", "continue"),
            });

            var response = await _client.PostAsync("/admin/Category/1/change/", formData);

            response.StatusCode.Should().Be(HttpStatusCode.Redirect);
            response.Headers.Location.ToString().Should().Contain("/admin/Category/1/change/");
        }

        [Fact]
        public async Task EditForm_RendersAutoGeneratedFields_AsReadOnlyTextAsync()
        {
            var response = await _client.GetAsync("/admin/Category/1/change/");
            var html = await response.Content.ReadAsStringAsync();

            response.StatusCode.Should().Be(HttpStatusCode.OK);

            // Id is value-generated (DatabaseGeneratedOption.Identity) so it should
            // render as read-only text, not an editable input field
            html.Should().Contain("readonly-value");
            html.Should().NotContain("name=\"Id\"",
                "auto-generated fields should not be rendered as form inputs");
        }

        [Fact]
        public async Task EditPost_SucceedsWithoutAutoGeneratedFieldsAsync()
        {
            // Sending only editable fields (no Id) should not cause a 500 error.
            // Before the fix, non-editable fields were rendered as readonly inputs
            // that submitted empty strings, causing DateTime parse failures.
            var formData = new FormUrlEncodedContent(new[]
            {
                new KeyValuePair<string, string>("Name", "Italian Verified"),
                new KeyValuePair<string, string>("Description", "Verified description"),
                new KeyValuePair<string, string>("_save_action", "save"),
            });

            var response = await _client.PostAsync("/admin/Category/2/change/", formData);

            response.StatusCode.Should().Be(HttpStatusCode.Redirect);
            response.Headers.Location.ToString().Should().Contain("/admin/Category/");
        }
    }
}
