using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.TestHost;
using NDjango.Admin.AspNetCore.AdminDashboard.Tests.Fixtures;
using Xunit;

namespace NDjango.Admin.AspNetCore.AdminDashboard.Tests.EntityCrudTests
{
    public class EditTests : IClassFixture<AdminDashboardFixture>
    {
        private readonly HttpClient _client;

        public EditTests(AdminDashboardFixture fixture)
        {
            _client = fixture.GetTestHost().GetTestClient();
        }

        [Fact]
        public async Task EditForm_RendersPrefilled_ForExistingRecordAsync()
        {
            // Category Id=1 is "Italian"
            var response = await _client.GetAsync("/admin/Category/1/change/");
            var html = await response.Content.ReadAsStringAsync();

            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
            Assert.Contains("Change category", html);
            Assert.Contains("Italian", html);
        }

        [Fact]
        public async Task EditForm_ContainsDeleteLinkAsync()
        {
            var response = await _client.GetAsync("/admin/Category/1/change/");
            var html = await response.Content.ReadAsStringAsync();

            Assert.Contains("/admin/Category/1/delete/", html);
            Assert.Contains("Delete", html);
        }

        [Fact]
        public async Task EditPost_UpdatesRecordAndRedirectsAsync()
        {
            var formData = new FormUrlEncodedContent(new[]
            {
                new KeyValuePair<string, string>("Name", "Italian Updated"),
                new KeyValuePair<string, string>("Description", "Updated description"),
                new KeyValuePair<string, string>("_save_action", "save"),
            });

            var response = await _client.PostAsync("/admin/Category/1/change/", formData);

            Assert.Equal(HttpStatusCode.Redirect, response.StatusCode);
            Assert.Contains("/admin/Category/", response.Headers.Location.ToString());
        }

        [Fact]
        public async Task EditPost_SaveAndContinue_RedirectsToSameFormAsync()
        {
            var formData = new FormUrlEncodedContent(new[]
            {
                new KeyValuePair<string, string>("Name", "Italian Final"),
                new KeyValuePair<string, string>("Description", "Final description"),
                new KeyValuePair<string, string>("_save_action", "continue"),
            });

            var response = await _client.PostAsync("/admin/Category/1/change/", formData);

            Assert.Equal(HttpStatusCode.Redirect, response.StatusCode);
            Assert.Contains("/admin/Category/1/change/", response.Headers.Location.ToString());
        }

        [Fact]
        public async Task EditForm_RendersAutoGeneratedFields_AsReadOnlyTextAsync()
        {
            var response = await _client.GetAsync("/admin/Category/1/change/");
            var html = await response.Content.ReadAsStringAsync();

            Assert.Equal(HttpStatusCode.OK, response.StatusCode);

            // Id is value-generated (DatabaseGeneratedOption.Identity) so it should
            // render as read-only text, not an editable input field
            Assert.Contains("readonly-value", html);
            Assert.DoesNotContain("name=\"Id\"", html);
        }

        [Fact]
        public async Task EditPost_SucceedsWithoutAutoGeneratedFieldsAsync()
        {
            // Sending only editable fields (no Id) should not cause a 500 error.
            // Before the fix, non-editable fields were rendered as readonly inputs
            // that submitted empty strings, causing DateTime parse failures.
            var formData = new FormUrlEncodedContent(new[]
            {
                new KeyValuePair<string, string>("Name", "Italian Verified"),
                new KeyValuePair<string, string>("Description", "Verified description"),
                new KeyValuePair<string, string>("_save_action", "save"),
            });

            var response = await _client.PostAsync("/admin/Category/2/change/", formData);

            Assert.Equal(HttpStatusCode.Redirect, response.StatusCode);
            Assert.Contains("/admin/Category/", response.Headers.Location.ToString());
        }
    }
}
